channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.9.3
- click=7.1.2
- dill=0.3.3
- gcsfs=0.7.1
- geckodriver=0.28.0
- leveldb=1.22
- multiprocess=0.70.11.1
- nodejs=14.15.1
- pandas=1.2.0
- pillow=8.1.0
- pip=20.3.3
- psutil=5.8.0
- pyarrow=2.0.0
- python=3.9.1
- pyvirtualdisplay=1.3.2
- redis-py=3.5.3
- s3fs=0.5.2
- selenium=3.141.0
- sentry-sdk=0.19.5
- tabulate=0.8.7
- tblib=1.6.0
- wget=1.20.1
- pip:
  - dataclasses-json==0.5.2
  - domain-utils==0.7.1
  - jsonschema==3.2.0
  - plyvel==1.3.0
name: openwpm
