channels:
    - conda-forge
dependencies:
    - black
    - codecov
    - pytest-cov
    - ipython
    - localstack==0.11.1.1 # See https://github.com/mozilla/OpenWPM/pull/682
    - pip
    - pre-commit
    - pytest
    - sphinx
    - pip:
        # Select depenedencies from localstack[full] that we need
        - amazon-kclpy
        - crontab
        - flask-cors
        - moto-ext==1.3.15.15 # See https://github.com/mozilla/OpenWPM/pull/682
        - subprocess32
        - nbsphinx
        - sphinx-autodoc-annotation
